---
- name: install netcat
  become: yes
  yum:
    name: nmap-ncat
    state: present
  tags:
    - zookeeper
    - bootstrap

- name: install wait script
  become: yes
  copy:
    src: zookeeper-wait-for-listen.sh
    dest: /usr/local/bin
    mode: 0755
  tags:
    - zookeeper

- name: generate default env file
  become: yes
  template:
    src: zookeeper-env.j2
    dest: "/etc/default/{{ zookeeper_service }}"
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: generate systemd service file
  become: yes
  template:
    src: zookeeper-service.j2
    dest: "/usr/lib/systemd/system/{{ zookeeper_service }}.service"
  notify:
    - register zookeeper service
    - reload systemd daemon
  tags:
    - zookeeper

- name: ensure zookeeper docker image is present
  become: yes
  command: docker pull {{ zookeeper_image }}:{{ zookeeper_image_tag }}
  tags:
    - zookeeper

- name: create zookeeper log directory
  become: yes
  file:
    path: /var/log/zookeeper
    state: directory
    mode: 0755
    setype: svirt_sandbox_file_t
  tags:
    - zookeeper

- name: install zookeeper scripts
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: zookeeper_check.sh
      dest: /usr/local/bin
  tags:
    - zookeeper

- name: generate zookeeper consul services
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: zk-consul.json.j2
      dest: /etc/consul/zk-consul.json
  notify:
    - reload consul
  tags:
    - zookeeper

- include: collectd.yml

- meta: flush_handlers

- name: ensure ZK is running
  become: yes
  service: 
    name: zookeeper
    state: started
  tags:
    - zookeeper

- include: distributive.yml
