---
# tasks file for redis
- name: Make redis user
  become: yes
  user: name=redis comment="redis"

- name: create folder for redis data
  become: yes
  file:
    name: /home/{{ item }}
    state: directory
    mode: 0755
    owner: redis
    group: redis
    recurse: yes
  with_items:
    - redis
    - redis/data
  tags:
    - redis

- name: copy redis.json file
  become: yes
  copy:
    dest: /usr/share/distributive/redis.json
    src: redis.json
  notify: restart redis container
  tags:
    - redis
    - consul

- name: ensure docker-redis docker image is present
  become: yes
  command: docker pull redis
#  notify: restart elastic-search container
  tags:
    - redis

- name: run the container
  become: yes
  docker:
    detach: yes
    docker_api_version: '1.20'
    image: redis
    name: redis
    ports:
      - 6379:6379
    restart_policy: always
    state: started
    volumes:
      - /home/redis/data:/data
      - /usr/share/distributive:/usr/share/distributive
      - /etc/distributive.d:/etc/distributive.d
  tags:
    - redis

- include: distributive.yml