---

- name: load the image into docker
  become: yes
  command: /usr/bin/docker load -i /tmp/{{ item | basename }}.tar
  with_items: "{{images}}"

- name: delete docker tar file
  file: path=/tmp/{{ item | basename }}.tar state=absent
  with_items: "{{images}}"

- name: tag docker image so it points to the remote registry
  become: yes
  command: /usr/bin/docker tag {{ item }} {{ destination }}:{{ port }}/{{ item | basename }}
  with_items: "{{images}}"

- name: push docker images to the remote registry
  become: yes
  command: /usr/bin/docker push {{ destination }}:{{ port }}/{{ item | basename }}
  with_items: "{{images}}" 