---
- name: ensure haproxy docker image is present
  become: yes
  command: /usr/bin/docker pull {{ haproxy_image }}:{{ haproxy_image_tag }}
  tags:
    - haproxy
    - bootstrap

- name: set haproxy environment
  become: yes
  template:
    src: haproxy.j2
    dest: /etc/default/haproxy
  notify:
    - restart haproxy
  tags:
    - haproxy

# - name: creat haproxy directory
#   become: yes
#   shell: "mkdir /etc/haproxy"

- name: copy entry script
  become: yes
  copy:
    src: entry.sh
    dest: /etc/haproxy/entry.sh


- name: copy initiation script
  become: yes
  copy:
    src: script.sh
    dest: /etc/haproxy/script.sh


- name: configure haproxy
  become: yes
  template:
    src: haproxy.service.j2
    dest: /usr/lib/systemd/system/haproxy.service
  notify:
    - reload haproxy
    - restart haproxy
  tags:
    - haproxy

- include: distributive.yml
