---

- name: make consul user
  become: yes
  user: name=consul comment="consul"

- name: install consul
  become: yes
  yum:
    name: https://dl.bintray.com/ciscocloud/rpm/consul-0.5.2-4.el7.centos.x86_64.rpm
    state: present
    disable_gpg_check: yes
  tags:
    - consul
    - bootstrap

- name: install consul-ui
  become: yes
  yum:
    name: https://dl.bintray.com/ciscocloud/rpm/consul-ui-0.5.2-4.el7.centos.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when: consul_is_server
  tags:
    - consul
    - bootstrap

- name: consul-utls
  become: yes
  yum:
    name: https://dl.bintray.com/ciscocloud/rpm/consul-utils-0.1.0-1.el7.centos.x86_64.rpm
    state: present
    disable_gpg_check: yes
  tags:
    - consul
    - bootstrap

- name: configure consul
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    force: "yes"
  with_items:
    - src: consul.json.j2
      dest: /etc/consul/consul.json
  notify:
    - restart consul
  tags:
    - consul

- name: register docker with consul
  become: yes
  copy:
    src: docker-service.json
    dest: /etc/consul
  notify:
    - reload consul
  tags:
    - consul

- name: deploy tls files
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: ssl/cacert.pem
      dest: /etc/consul/ssl/{{ consul_ca_file }}
    - src: ssl/certs/consul.cert.pem
      dest: /etc/consul/ssl/{{ consul_cert_file }}
    - src: ssl/private/consul.key.pem
      dest: /etc/consul/ssl/{{ consul_key_file }}
  notify:
    - restart consul
  tags:
    - consul

- name: configure consul acl policy
  become: yes
  template:
    src: acl.json.j2
    dest: /etc/consul/acl.json
  notify:
    - restart consul
  tags:
    - consul

- name: install consul scripts
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: consul-wait-for-leader.sh
      dest: /usr/local/bin
    - src: consul-rolling-restart.sh
      dest: /usr/local/bin
  tags:
    - consul

- name: install check scripts
  become: yes
  copy:
    src: check-service-active
    dest: /usr/local/bin
    mode: 0755
  tags:
    - consul

- name: enable consul
  become: yes
  service:
    name: consul
    enabled: yes
    state: started
  tags:
    - consul

# Give consul time to elect a leader
- name: wait for leader
  command: /usr/local/bin/consul-wait-for-leader.sh
  tags:
    - consul

- meta: flush_handlers

- include: acl.yml

- meta: flush_handlers

- include: nginx_proxy.yml

# symlink to distributive checklist, register check with Consul
- include: distributive.yml