---
- name: set logrotate interval to daily
  become: yes
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^weekly'
    line: "daily"
    backrefs: yes
  tags:
    - logrotate

- name: set logrotate retention period to 7 days
  become: yes
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^rotate 4'
    line: "rotate 7"
    backrefs: yes
  tags:
    - logrotate

- name: configure mesos logrotate
  become: yes
  copy:
    src: mesos
    dest: /etc/logrotate.d/mesos
    mode: 0644
    owner: root
    group: root
  tags:
    - logrotate

- name: create mesos archive
  become: yes
  file:
    path: /var/log/mesos/archive
    mode: 0755
    state: directory
  tags:
    - logrotate

- name: configure docker logrotate
  become: yes
  copy:
    src: docker
    dest: /etc/logrotate.d/docker
    mode: 0644
    owner: root
    group: root
  tags:
    - logrotate

- name: create docker archive
  become: yes
  file:
    path: /var/log/docker/archive
    mode: 0755
    state: directory
  tags:
    - logrotate

- name: configure zookeeper logrotate
  become: yes
  copy:
    src: zookeeper
    dest: /etc/logrotate.d/zookeeper
    mode: 0644
    owner: root
    group: root
  when: "'role=control' in group_names"
  tags:
    - logrotate

- name: create zookeeper archive
  become: yes
  file:
    path: /var/log/zookeeper/archive
    mode: 0755
    state: directory
  when: "'role=control' in group_names"
  tags:
    - logrotate
