---
galaxy_info:
  author: Ankur Shah
  description: Installs redis
  #company: your company (optional)
  # Some suggested licenses:
  # - MIT
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: EL
    versions:
      - 7
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.