---
# tasks file for kibana

- name: run the container
  become: yes
  docker:
    detach: yes
    docker_api_version: '1.20'
    env:
      ELASTICSEARCH_URL: "http://pe-dev3.ishisystems.com:9200"
    image: pe-dev3.ishisystems.com:5000/kibana:0.1
    name: kibana
    ports:
      - 5601:5601
    restart_policy: always
    state: started
  tags:
    - kibana
