---
- name: reload glusterfs
  become: yes
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl restart glusterd
    - systemctl restart glusterfsd

- name: reload consul
  become: yes
  command: "consul reload"