---
- name: add mesosphere repository
  become: yes
  yum:
    name:  http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state: present
  tags:
    - mesos
    - bootstrap

- name: install mesos package
  become: yes
  yum:
    name: "{{ mesos_package }}"
    state: present
  tags:
    - mesos
    - bootstrap

- name: add mesos user
  become: yes
  user:
    name: mesos
    comment: "mesos"

- name: install cyrus-sasl-md5
  become: yes
  yum:
    name: cyrus-sasl-md5
    state: present
  tags:
    - mesos
    - bootstrap

- name: configure /etc/mesos/zk
  become: yes
  template:
    src: zk.j2
    dest: /usr/etc/mesos/zk
  tags:
    - mesos

- name: configure /etc/mesos/hostname
  become: yes
  template:
    src: hostname.j2
    dest: /usr/etc/mesos/hostname
    mode: 0600
  tags:
    - mesos

- name: disable mesos leader
  become: yes
  service:
    name: mesos-master
    enabled: no
  when: mesos_mode == "follower"
  tags:
    - mesos

- name: configure mesos-master unit file
  become: yes
  replace:
    dest: /usr/lib/systemd/system/mesos-master.service
    regexp: "=network.target"
    replace: '=zookeeper.service'
  when: mesos_mode == "leader"
  tags:
    - mesos

- name: disable mesos follower
  become: yes
  service:
    name: mesos-slave
    enabled: no
  when: mesos_mode == "leader"
  tags:
    - mesos

- name: ensure consul.d is present
  become: yes
  file:
    path: "{{ consul_dir }}"
    state: directory
  tags:
    - mesos

# - include: leader.yml
#   when: mesos_mode == "leader" or mesos_mode == "mixed"

# - include: follower.yml
#   when: mesos_mode == "follower" or mesos_mode == "mixed"
