- name: restart nginx-mantlui
  become: yes
  service:
    name: nginx-mantlui
    state: restarted
  tags:
    - mantlui

- name: reload nginx-mantlui
  become: yes
  command: systemctl daemon-reload
  tags:
    - mantlui
