---
- name: restart mesos leader
  become: yes
  command: systemctl restart mesos-master

- name: remove mesos follower metadata
  become: yes
  command: "{{ item }}"
  with_items:
    - systemctl stop mesos-slave
    - rm -rf /tmp/mesos/meta/slaves/latest
    - systemctl start mesos-slave

- name: restart mesos follower
  become: yes
  command: systemctl restart mesos-slave

- name: reload consul
  become: yes
  command: "{{ consul_bin }} reload"

- name: restart nginx-mesos-leader
  become: yes
  command: systemctl restart nginx-mesos-leader

- name: reload nginx-mesos-leader
  become: yes
  command: systemctl daemon-reload

- name: restart collectd
  become: yes
  service:
    name: collectd
    state: restarted
