---
- name: Install PIP
  yum: pkg=python-pip state=installed update_cache=true
  tags:
    - elastic-search

- name: Install Python HTTPLib
  sudo: true
  pip:
    name: httplib2
    state: present
    extra_args: '--proxy https://tel-proxy.yaanatech.net:3128'
  tags:
    - elastic-search

- name: Add Elasticsearch repository.
  sudo: true
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
  tags:
      - elastic-search

- name: Install Elasticsearch
  sudo: true
  yum: pkg=elasticsearch state=installed update_cache=yes
  tags:
      - elastic-search

# Run sudo update-rc.d elasticsearch defaults 95 10
- name: Enable Elasticsearch (Start on boot)
  sudo: true
  service:
    name: elasticsearch
    enabled: yes
  notify:
   - Start Elasticsearch
  tags:
     - elastic-search

- name: Configure Elasticsearch
  sudo: true
  template: 
    src: elasticsearch.yml.j2 
    dest: /etc/elasticsearch/elasticsearch.yml
  tags:
    - configs
    - elastic-search
  notify:
   - Restart Elasticsearch