---
# tasks file for elastic-search

- name: copy config file
  sudo: yes
  copy:
    dest: /opt/elasticsearch/config
    mode: 0644
    src: logging.yml
    backup: yes
  notify: restart elastic-search container
  tags:
    - elastic-search

- name: setup docker drop in config file
  sudo: yes
  template:
    src: elasticsearch.yml.j2
    dest: /opt/elasticsearch/config
    mode: 0644
    backup: yes
  notify: restart elastic-search container
    tags:
      - elastic-search

- name: run the container
  sudo: yes
  docker:
    detach: yes
    docker_api_version: '1.20'
    image: "{{ docker_registry_fqdn }}:{{ docker_registry_port }}/elastic-search:v0.1"
    name: "{{ elastic_search_container_name }}"
    ports:
      - 9200:9200
      - 9300:9300
    restart_policy: always
    state: started
    volumes:
      - "/var/elasticsearch/config" : "/opt/elasticsearch/config"
  tags:
    - elastic-search