---
- name: restart networkmanager
  become: yes
  command: systemctl restart NetworkManager

- name: restart dnsmasq
  become: yes
  command: systemctl restart dnsmasq

- name: reload consul
  become: yes
  command: "/bin/consul reload"