---
- name: install consul-template
  sudo: yes
  yum:
    name: consul-template
    state: present
  tags:
    - consul-template
    - bootstrap

- name: configure consul-template
  sudo: yes
  copy:
    src: consul.cfg
    dest: /etc/consul-template/config.d
  notify:
    - reload consul-template
  tags:
    - consul-template

- name: enable consul-template
  sudo: yes
  service:
    name: consul-template
    enabled: yes
    state: started
  tags:
    - consul-template
