---
- name: install consul-template
  become: yes
  yum:
    name: https://bintray.com/artifact/download/asteris/mantl-rpm/consul-template-0.12.2-1.x86_64.rpm
    state: present
  tags:
    - consul-template
    - bootstrap

- name: configure consul-template
  become: yes
  copy:
    src: consul.cfg
    dest: /etc/consul-template/config.d
  notify:
    - reload consul-template
  tags:
    - consul-template

- name: enable consul-template
  become: yes
  service:
    name: consul-template
    enabled: yes
    state: started
  tags:
    - consul-template
