---
# handlers file for elastic-search

- name: restart elastic-search container
  command: docker restart {{ elastic_search_container_name }}
  become: yes

- name: reload consul
  become: yes
  command: "{{ consul_bin }} reload"