---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  become: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive
    - vault

- name: create symlink to distributive vault checklist
  become: yes
  file:
    state: link
    src: /usr/share/distributive/vault.json
    dest: /etc/distributive.d/vault.json
  tags:
    - consul
    - distributive
    - vault

- name: register distributive tests with consul
  become: yes
  copy:
    src: distributive-vault-check.json
    dest: /etc/consul/
  notify:
    - reload consul
  tags:
    - consul
    - distributive
    - vault
