---
- name: reload marathon
  become: yes
  command: systemctl daemon-reload
  notify:
    - wait for marathon to listen

- name: restart marathon
  become: yes
  command: systemctl restart marathon
  notify:
    - wait for marathon to listen

- name: wait for marathon to listen
  command: /usr/local/bin/marathon-wait-for-listen.sh

- name: reload consul
  become: yes
  command: "{{ consul_bin }} reload"

- name: restart nginx-marathon
  become: yes
  command: systemctl restart nginx-marathon

- name: reload nginx-marathon
  become: yes
  command: systemctl daemon-reload

- name: restart collectd
  become: yes
  service:
    name: collectd
    state: restarted
