- name: create folder for certificate
  become: yes
  file:
    name: /etc/docker/certs.d/{{ docker_registry_fqdn }}:{{ docker_registry_hostport }}
    state: directory
    mode: 0755
  tags:
    - docker-registry-client

- name: copy cert file to docker certs
  become: yes
  copy:
    dest: /etc/docker/certs.d/{{ docker_registry_fqdn }}:{{ docker_registry_hostport }}/ca.crt
    mode: 0400
    src: ssl/docker-registry.crt
    backup: yes
  tags:
    - docker-registry-client

- name: copy registry cert file
  become: yes
  copy:
    dest: /etc/pki/ca-trust/source/anchors/pe-dev3.ishisystems.com.crt
    src: ssl/docker-registry.crt
  notify: update-ca-trust
  tags:
    - docker-registry-client