---
# Workaround for https://github.com/CiscoCloud/microservices-infrastructure/issues/161
- name: install latest device-mapper-libs
  sudo: yes
  yum:
    name: device-mapper-libs
    state: latest
  tags:
    - docker
    - bootstrap

- name: install docker repo
  sudo: yes
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
  tags:
    - docker
    - bootstrap

- name: install docker packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-1.7.1
    - docker-selinux-1.7.1
  tags:
    - docker
    - bootstrap

- name: create rsyslog.d
  sudo: yes
  file:
    dest: /etc/rsyslog.d
    state: directory
  tags:
    - docker
    - bootstrap

- name: create docker entry for syslogd
  sudo: yes
  copy:
    dest: /etc/rsyslog.d/10-docker.conf
    content: |
      # Docker logging
      :syslogtag, isequal, "docker:"  /var/log/docker/docker.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - docker
    - bootstrap

- name: setup env specific docker options
  sudo: yes
  template:
    src: docker-local.j2
    dest: /etc/sysconfig/docker-local
    mode: 0644
  notify:
    - reload docker
  tags:
    - docker

- name: setup docker drop in config file
  sudo: yes
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker
    mode: 0644
  notify:
    - reload docker
  tags:
    - docker

- name: ensure docker-storage is using devicemapper and lvm
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker-storage
    regexp: ^DOCKER_STORAGE_OPTIONS=
    line: DOCKER_STORAGE_OPTIONS=--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/pri-docker--pool --storage-opt dm.use_deferred_removal=true
    state: present
    create: yes
  notify:
    - reload docker
  tags:
    - docker

- name: add docker-local options to existing docker config
  sudo: yes
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    regexp: ^ExecStart=/usr/bin/docker 
    line: ExecStart=/usr/bin/docker -d $OPTIONS $other_arg \\
    state: present
    create: yes
  notify:
    - reload docker
  tags:
    - docker

- name: create docker.system.d
  sudo: yes
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory
  tags:
    - docker

- name: create local docker service override
  sudo: yes
  copy:
    dest: /etc/systemd/system/docker.service.d/local.conf
    content: |
      [Service]
      EnvironmentFile=-/etc/sysconfig/docker-local
  notify:
    - reload docker
  tags:
    - docker

- name: ensure docker config dir exists
  sudo: yes
  file:
    path: /root/.docker
    state: directory
  tags:
    - docker

- name: setup private docker registry credentials
  sudo: yes
  when: do_private_docker_registry
  template:
    src: config.json.j2
    dest: /root/.docker/config.json
  tags:
    - docker

- name: add docker registry credentials to /etc/
  sudo: yes
  when: do_private_docker_registry
  command: tar cvzf /etc/docker.tar.gz .docker
  args:
    chdir: /root
  tags:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap

- include: collectd.yml
