---

- name: save the image to the tar file
  become: yes
  command: "/usr/bin/docker save -o /tmp/{{ item | basename }}.tar {{ item }}"
  with_items: "{{images}}"  

# - name: copy docker image tar file to remote machine
#   become: yes
#   synchronize: mode=pull src=pe-dev1.ishisystems.com:/home/images/{{ item }}.tar dest=pe-dev2.ishisystems.com:/home/images/{{ item }}.tar
#   delegate_to: pe-dev1.ishisystems.com
#   with_items: "{{images}}"

- name: copy docker tar file
  command: scp -P {{ ssh_port }} /tmp/{{ item | basename }}.tar {{ username }}@{{ destination }}:/tmp/{{ item | basename }}.tar
  with_items: "{{images}}"  

- name: delete docker tar file
  become: yes
  file: path=/tmp/{{ item | basename }}.tar state=absent
  with_items: "{{images}}"

